name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6  # Specify the Terraform version to use

      # Step 3: Initialize Terraform (downloads plugins and initializes the backend)
      - name: Terraform Init
        run: terraform init

      # Step 4: Apply the Terraform configuration (automatically approve changes)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 5: Install Python dependencies (for testing)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests  # Install boto3 and requests for the testing script

      # Step 6: Run tests on the infrastructure
      - name: Run tests on infrastructure
        run: python test_infrastructure.py  # Run the Python test script that verifies EC2 and AppDynamics agent status

      # 5. Deploy to AWS (optional)
      - name: Deploy to AWS
        run: |
          aws s3 cp ./build/ s3://deploymentbucket321/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
