name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # or macos-latest if using macOS

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python (use the Python version that works best for your project)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # You can try changing the Python version if needed

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip cache purge  # Clear the pip cache
          pip install --no-cache-dir -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: |
          pytest

      # 5. Deploy to AWS (optional)
      - name: Deploy to AWS
        run: |
          aws s3 cp ./build/ s3://deploymentbucket321/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
